### PR TITLE
Fix image referrences, fix small formatting issue, fix image submit/delete

### LINKED ISSUE #177: Delete image on submit, not on click "x"
If you click x on an image then cancel, the image is already deleted.

### PR DESCRIPTION
**Pull request by caitlin-hutnyk**
Resolve #177, #178, #180

### CODE REVIEW

File: public/javascripts/editneumescript.js [hunk 1]
```diff
@@ -27,6 +27,12 @@ function initEditNeume(neume) {
     //Getting the canvas for the images : 
     var images = neume.imagesBinary;
 
+    // the form can't be submitted if the input empty
+    // or if it is an empty array or empty string
+    // so we have to use some non-empty string as default input
+    var imagesToDelete = 'none';
+    document.getElementById("imageToDelete" + neume._id).value = imagesToDelete;
```
Comment (JRegimbal) [inline public/javascripts/editneumescript.js]: Possibility of an error if `document.getElementById("imageToDelete" + neume._id)` returns `null`.

File: public/javascripts/editneumescript.js [hunk 2]
```diff
@@ -85,27 +90,18 @@ function initEditNeume(neume) {
...
+        buttonDeleteImage.onclick = ('click', function() {
+            if (imagesToDelete == 'none') {
+                imagesToDelete = [];
+            }
+            imagesToDelete.push(element);
+            document.getElementById("imageToDelete" + neume._id).value = imagesToDelete;
             //Delete the image :
             canvas.style.display = "none";
             buttonDeleteImage.style.display = "none";
         })
```
Comment (JRegimbal) [inline public/javascripts/editneumescript.js]: Does this work? Typically `onclick` is assigned to a function rather than what seems to be a tuple here. Also, is there a reason to set an attribute rather than use `addEventListener`?

File: public/javascripts/editneumescript.js [hunk 3]
```diff
@@ -85,27 +90,18 @@ function initEditNeume(neume) {
...
         imageCard.appendChild(buttonDeleteImage);
-        $(buttonDeleteImage).click(function() {
-            document.getElementById("imageToDelete" + neume._id).value = element;
-            $("#deleteImagebutton" + neume._id).click();
+        buttonDeleteImage.onclick = ('click', function() {
+            if (imagesToDelete == 'none') {
+                imagesToDelete = [];
+            }
+            imagesToDelete.push(element);
+            document.getElementById("imageToDelete" + neume._id).value = imagesToDelete;
```
Comment (JRegimbal) [inline public/javascripts/editneumescript.js]: Same concern about `null`

File: views/projects/showproject.jade [hunk 4]
```diff
@@ -178,13 +172,13 @@ div.neumeSection(style = "padding-bottom : 3px; padding-top : 97px")
...
+      h5(style = " font: 15px Avenir, sans-serif; text-align: center;") Images
     .column(style='background-color:#afcfee; width : 20%; border-right : #819fff; border-width : 1px; border-style : solid; border-left : none; border-bottom : none;  border-top : none;')
-      h5(style = " font: 18px Avenir, sans-serif; text-align: center;") Folio 
+      h5(style = " font: 15px Avenir, sans-serif; text-align: center;") Folio 
     .column(style='background-color:   #afcfee; width : 20%; border-right : #819fff; border-width : 1px; border-style : solid; border-left : none; border-bottom : none;  border-top : none;')
-      h5(style = " font: 18px Avenir, sans-serif; text-align: center;") Classification
+      h5(style = " font: 15px Avenir, sans-serif; text-align: center;") Classification
     .column(style='background-color:#afcfee; width : 35% ; right : 110px')
-      h5(style = "font: 18px Avenir, sans-serif; text-align: center;") MEI encoding
+      h5(style = "font: 15px Avenir, sans-serif; text-align: center;") MEI encoding
```
Comment (JRegimbal) [inline views/projects/showproject.jade:181]: Not for this PR, but all of this stuff really ought to be in a stylesheet.

File: routes/neumes.js [hunk 5]
```diff
@@ -242,83 +248,39 @@ router.route('/:id/editImage')
...
+            mongoose.model('neume').findOneAndUpdate({
+                _id: req.id
+            }, {
+                $pull: {
+                    imagesBinary: { $in: imagesToDelete }
+                }
+            }, function(err, data) {
+                logger.log(err, data);
+                mongoose.model('storedImages').deleteMany({
+                    imgBase64: { $in: imagesToDelete }
```
Comment (JRegimbal) [inline routes/neumes.js:270]: I think it'd be useful to add a high-level comment for what is happening with the mongoose stuff here.

**Review by JRegimbal — COMMENTED** [review]
Changes look good to me, although there are some things I think should be checked or clarified.
